"""Add hs_codes, fta_rates, data_versions tables

Revision ID: 5eae795c2eff
Revises:
Create Date: 2026-01-27 10:39:05.958354+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5eae795c2eff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # Enable pg_trgm extension for trigram full-text search
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')

    op.create_table('data_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hs_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('description_vn', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('duty_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('vat_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('policy_notes', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('data_version_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_version_id'], ['data_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hs_codes_code'), 'hs_codes', ['code'], unique=True)
    op.create_index(op.f('ix_hs_codes_data_version_id'), 'hs_codes', ['data_version_id'], unique=False)

    # Add GIN trigram indexes for full-text search
    op.execute('CREATE INDEX idx_hs_codes_description_vn_trgm ON hs_codes USING GIN (description_vn gin_trgm_ops)')
    op.execute('CREATE INDEX idx_hs_codes_description_en_trgm ON hs_codes USING GIN (description_en gin_trgm_ops)')

    op.create_table('fta_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hs_code_id', sa.Integer(), nullable=False),
    sa.Column('agreement_code', sa.String(length=20), nullable=False),
    sa.Column('preferential_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fta_rates_agreement_code'), 'fta_rates', ['agreement_code'], unique=False)
    op.create_index(op.f('ix_fta_rates_hs_code_id'), 'fta_rates', ['hs_code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fta_rates_hs_code_id'), table_name='fta_rates')
    op.drop_index(op.f('ix_fta_rates_agreement_code'), table_name='fta_rates')
    op.drop_table('fta_rates')

    # Drop trigram indexes
    op.execute('DROP INDEX IF EXISTS idx_hs_codes_description_en_trgm')
    op.execute('DROP INDEX IF EXISTS idx_hs_codes_description_vn_trgm')

    op.drop_index(op.f('ix_hs_codes_data_version_id'), table_name='hs_codes')
    op.drop_index(op.f('ix_hs_codes_code'), table_name='hs_codes')
    op.drop_table('hs_codes')
    op.drop_table('data_versions')

    # Drop extensions (be careful - other migrations might use these)
    op.execute('DROP EXTENSION IF EXISTS pg_trgm')
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###
